import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
const m = vi.hoisted(() => ({ settings: vi.fn(), remove: vi.fn(), date: vi.fn() }))
vi.mock('../../electron/main/database/settingsRepository', () => ({ getSettings: m.settings }))
vi.mock('../../electron/main/database/briefingRepository', () => ({ deleteOldBriefings: m.remove }))
vi.mock('../../electron/main/utils/dateUtils', () => ({ utcToBjDate: m.date }))
let cleaner: typeof import('../../electron/main/services/cleanerService')
beforeEach(async () => {
  vi.resetModules()
  vi.resetAllMocks()
  vi.useFakeTimers()
  m.settings.mockReturnValue({ retentionDays: 30 })
  m.remove.mockReturnValue(0)
  m.date.mockReturnValue('2026-10-08')
  cleaner = await import('../../electron/main/services/cleanerService')
})
afterEach(() => { cleaner.stopDailyCleanup(); vi.clearAllTimers(); vi.useRealTimers() })
describe('owned hourly cleaner', () => {
  it('repeated start owns a single interval and cleans once per Beijing date', async () => {
    cleaner.scheduleDailyCleanup()
    cleaner.scheduleDailyCleanup()
    expect(vi.getTimerCount()).toBe(1)
    await vi.advanceTimersByTimeAsync(3_600_000)
    expect(m.remove).toHaveBeenCalledTimes(1)
    m.date.mockReturnValue('2026-10-09')
    await vi.advanceTimersByTimeAsync(3_600_000)
    expect(m.remove).toHaveBeenCalledTimes(2)
    expect(m.remove).toHaveBeenLastCalledWith(30)
  })
  it('stop is idempotent and no old interval runs on the following day', async () => {
    cleaner.scheduleDailyCleanup()
    cleaner.stopDailyCleanup()
    cleaner.stopDailyCleanup()
    m.date.mockReturnValue('2026-10-09')
    await vi.advanceTimersByTimeAsync(86_400_000)
    expect(vi.getTimerCount()).toBe(0)
    expect(m.remove).toHaveBeenCalledTimes(1)
  })
  it('restart keeps daily cleanup deduplication and creates one interval', () => {
    cleaner.scheduleDailyCleanup()
    cleaner.stopDailyCleanup()
    cleaner.scheduleDailyCleanup()
    expect(m.remove).toHaveBeenCalledTimes(1)
    expect(vi.getTimerCount()).toBe(1)
  })
  it('failed initial cleanup does not leave an interval and can be retried', () => {
    m.remove.mockImplementationOnce(() => { throw new Error('isolated retention failure') })
    expect(() => cleaner.scheduleDailyCleanup()).toThrow('isolated retention failure')
    expect(vi.getTimerCount()).toBe(0)
    cleaner.scheduleDailyCleanup()
    expect(vi.getTimerCount()).toBe(1)
    expect(m.remove).toHaveBeenCalledTimes(2)
  })
})
